using UnityEngine;

public class PlayerStats : MonoBehaviour
{
    private int
        maxHealth = 250, 
        currentHealth, 
        maxShield = 100,
        shield;

    [SerializeField] private float power = 5f;
    public float Power => power;

    Animator animator;

    private void Start()
    {
        animator = GetComponentInChildren<Animator>();
        currentHealth = maxHealth;
        shield = maxShield; // Initialize shield to maximum value   
    }

    public void TakeDamage(int amount)
    {
        animator.SetTrigger("Damaged");
        Debug.Log("Player took " + amount + "damage");
        if(shield > 0)
        {
            shield -= amount;
            if(shield < 0)
            {
                shield = 0; // Ensure shield does not go below 0
            }
        }
        else
        {

            currentHealth -= amount;
            
        }

        if(currentHealth <= 0)
        {
            currentHealth = 0; // Ensure health does not go below 0
            Debug.Log("Player is dead!");
            // Handle player death (e.g., trigger game over, respawn, etc.)
        }
    }

    public void RegenShield()
    {
        if (shield < maxShield)
        {
            shield += maxShield; // Regenerate shield by 20 points
            if (shield > maxShield)
            {
                shield = maxShield; // Ensure shield does not exceed maximum value
            }
            Debug.Log("Shield regenerated by 20 points!");
        }
        else
        {
            Debug.Log("Shield is already at maximum value.");
        }
    }
}
