using UnityEngine;

public class PlayerStats : MonoBehaviour
{
    private int
        maxHealth = 250,
        maxShield = 100,
        shield;

    [SerializeField] private int currentHealth;

    [SerializeField] private float power = 5f;
    public float Power => power;
    public bool iFrame = false; // Invincibility frame flag

    Animator animator;

    [SerializeField] SpriteRenderer playerHeadRenderer;
    [SerializeField] SpriteRenderer playerbodyRenderer;

    [SerializeField] Sprite playerHead1;
    [SerializeField] Sprite playerBody1;


    [SerializeField] Sprite playerHead2;
    [SerializeField] Sprite playerBody2;


    [SerializeField] Sprite playerHead3;
    [SerializeField] Sprite playerBody3;


    private void Start()
    {
        animator = GetComponentInChildren<Animator>();
        currentHealth = maxHealth;
        shield = maxShield; // Initialize shield to maximum value   
    }

    private void Update()
    {
        ChangeSprites();
    }

    public void TakeDamage(int amount)
    {
        animator.SetTrigger("Damaged");
        Debug.Log("Player took " + amount + "damage");
        if (iFrame)
        {
            Debug.Log("Player is invincible, no damage taken.");
            return; // If player is invincible, ignore damage
        }
        if (shield > 0)
        {
            shield -= amount;
            if(shield < 0)
            {
                shield = 0; // Ensure shield does not go below 0
            }
        }
        else
        {
            currentHealth -= amount;  
        }
        if (currentHealth <= 0)
        {
            currentHealth = 0; // Ensure health does not go below 0
            Debug.Log("Player is dead!");
            // Handle player death (e.g., trigger game over, respawn, etc.)
            GameManager.instance.HandleDeath();
        }
    }

    public void ChangeSprites()
    {
        if (currentHealth < 100)
        {
            playerHeadRenderer.sprite = playerHead3;
            playerbodyRenderer.sprite = playerBody3;
        }
        else if (currentHealth < 200)
        {
            playerHeadRenderer.sprite = playerHead2;
            playerbodyRenderer.sprite = playerBody2;
        }
        else // Above 50% health (healthy state)
        {
            playerHeadRenderer.sprite = playerHead1;
            playerbodyRenderer.sprite = playerBody1;
        }
    }

    public void RegenShield()
    {
        if (shield < maxShield)
        {
            shield += maxShield; // Regenerate shield by 20 points
            if (shield > maxShield)
            {
                shield = maxShield; // Ensure shield does not exceed maximum value
            }
            Debug.Log("Shield regenerated by 20 points!");
        }
        else
        {
            Debug.Log("Shield is already at maximum value.");
        }
    }
}
