using UnityEngine;

public class ShieldRegen : MonoBehaviour
{
    GameObject player;
    public int regenerationRate = 20; // Time in seconds between regenerations

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.CompareTag("Player"))
        {
            player = collision.gameObject;
            PlayerStats playerStats = player.GetComponentInParent<PlayerStats>();
            if (playerStats != null)
            {
                if (playerStats.shield < playerStats.maxShield)
                {
                    playerStats.shield += playerStats.maxShield; // Regenerate shield by 20 points
                    if (playerStats.shield > playerStats.maxShield)
                    {
                        playerStats.shield = playerStats.maxShield; // Ensure shield does not exceed maximum value
                    }
                    Debug.Log("Shield regenerated by 20 points!");
                }
                else
                {
                    Debug.Log("Shield is already at maximum value.");
                }
            }
            else
            {
                Debug.LogWarning("PlayerStats component not found on the player object.");
            }
        }
    }
}
